### ISSUE TITLE
it doesn't check gem install error

### ISSUE THREAD

**Issue by byplayer** [MurgaNikolay/chef-rvm#3]
If I set gem and gem install fail, but there is no error.

**Comment by byplayer** [comment]
I send pull request and #4 issue was created.

**Comment by NikolayMurha** [comment]
Hi. Thanks for pull request. 
I'm a little busy, and I will do it next week.
I prepare refactoring, and I want to simplify the libraries and improve performance.
I'm sure I will consider your request.
Thanks.

**Comment by byplayer** [comment]
Thank you.
I'm looking forward to new version :)

**Comment by NikolayMurha** [comment]
New version are ready.

**Comment by byplayer** [comment]
Thanks !
