### ISSUE TITLE
chef-rvm version in supermarket older than Github version

### ISSUE THREAD

**Issue by saagar** [MurgaNikolay/chef-rvm#8]
we're using your chef-rvm cookbook, but the supermarket version is 0.4.9. Are you planning on bumping it there, or should we use the latest version from here?

**Comment by mateomurphy** [comment]
Seems the cookbook was renamed, this version is up to date: https://supermarket.chef.io/cookbooks/chef_rvm

**Comment by saagar** [comment]
ah thanks!
