### ISSUE TITLE
keyserver.ubuntu.com is not accessible via ipv6

### ISSUE THREAD

**Issue by aogail** [MurgaNikolay/chef-rvm#9]
I am attempting to use `chef_rvm` on a host that only has ipv6 Internet access, no ipv4. Because `chef_rvm` imports a GPG key from `keyserver.ubuntu.com`, the import fails. `keyserver.ubuntu.com` [is not available via ipv6](https://answers.launchpad.net/launchpad/+question/189094).

I would suggest switching to `keys.gnupg.net` which is available via ipv6 and is the host used in RVM's installation docs.

**Comment by NikolayMurha** [comment]
Try version 1.1.0. I  added node['chef_rvm']['keyserver'] attribute.
Default value is `hkp://keyserver.ubuntu.com` but you can set `hkp://keys.gnupg.net`
